kind: pipeline
name: check-app-compatbility

steps:
  - name: check-app-compatbility
    image: nextcloudci/php7.1:php7.1-16
    environment:
      APP_NAME: limit_login_to_ip
      CORE_BRANCH: master
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server

      # Code checker
      - ./occ app:check-code $APP_NAME -c strong-comparison
      - ./occ app:check-code $APP_NAME -c deprecation

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: integration-tests

steps:
  - name: integration-tests
    image: nextcloudci/php7.1:php7.1-16
    environment:
      APP_NAME: limit_login_to_ip
      CORE_BRANCH: master
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php occ app:enable limit_login_to_ip
      - php -S 127.0.0.1:8080 &
      - cd apps/limit_login_to_ip/tests/integration/ && vendor/bin/behat

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
